apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: icgroup
  labels:
    app: odoo
    env: prod
spec:
  selector:
    app: odoo
  ports:
    - port: 8069
      targetPort: 8069
      protocol: TCP
      nodePort: 30082
  type: NodePort