apiVersion: v1
kind: Service
metadata:
  name: ic-webapp
  namespace: icgroup
  labels:
    app: ic-webapp
    env: prod
spec:
  type: NodePort
  selector:
    app: ic-webapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  