apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
spec:
  selector:
    app: pgadmin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081         
  type: NodePort